name: Ephemeral Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ephemeral]
    strategy:
      matrix:
        python-version: [3.9,3.10,3.11,3.12,3.13]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Running on ephemeral runner jou"
          hostname
